<?php
return [
	'tables' => [
		'comment_result' => [
			'name' => 'comment_result',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'comment_id' => [
					'cid' => 1,
					'name' => 'comment_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'result_id' => [
					'cid' => 2,
					'name' => 'result_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'special_value' => [
					'cid' => 3,
					'name' => 'special_value',
					'type' => 'decimal(8,2)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 4,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 5,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'comments' => [
			'name' => 'comments',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'wording' => [
					'cid' => 1,
					'name' => 'wording',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'abbr' => [
					'cid' => 2,
					'name' => 'abbr',
					'type' => 'varchar(255)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'details' => [
					'cid' => 3,
					'name' => 'details',
					'type' => 'TEXT',
					'notnull' => 0,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'parameter_id' => [
					'cid' => 4,
					'name' => 'parameter_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'value' => [
					'cid' => 5,
					'name' => 'value',
					'type' => 'decimal(8,2)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'relative' => [
					'cid' => 6,
					'name' => 'relative',
					'type' => 'tinyint(1)',
					'notnull' => 1,
					'dflt_value' => '\'1\'',
					'pk' => 0,
				],
				'proportional' => [
					'cid' => 7,
					'name' => 'proportional',
					'type' => 'tinyint(1)',
					'notnull' => 1,
					'dflt_value' => '\'0\'',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 8,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 9,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'course_semester' => [
			'name' => 'course_semester',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'course_id' => [
					'cid' => 1,
					'name' => 'course_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'semester_id' => [
					'cid' => 2,
					'name' => 'semester_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 3,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 4,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'courses' => [
			'name' => 'courses',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'code' => [
					'cid' => 1,
					'name' => 'code',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'title' => [
					'cid' => 2,
					'name' => 'title',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'abbr' => [
					'cid' => 3,
					'name' => 'abbr',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'slug' => [
					'cid' => 4,
					'name' => 'slug',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'department_id' => [
					'cid' => 5,
					'name' => 'department_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 6,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 7,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'departments' => [
			'name' => 'departments',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'code' => [
					'cid' => 1,
					'name' => 'code',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'name' => [
					'cid' => 2,
					'name' => 'name',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'abbr' => [
					'cid' => 3,
					'name' => 'abbr',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'slug' => [
					'cid' => 4,
					'name' => 'slug',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'school_id' => [
					'cid' => 5,
					'name' => 'school_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 6,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 7,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'evaluation_teacher' => [
			'name' => 'evaluation_teacher',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'evaluation_id' => [
					'cid' => 1,
					'name' => 'evaluation_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'teacher_id' => [
					'cid' => 2,
					'name' => 'teacher_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'role' => [
					'cid' => 3,
					'name' => 'role',
					'type' => 'INT',
					'notnull' => 1,
					'dflt_value' => '\'1\'',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 4,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 5,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'evaluations' => [
			'name' => 'evaluations',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'title' => [
					'cid' => 1,
					'name' => 'title',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'description' => [
					'cid' => 2,
					'name' => 'description',
					'type' => 'TEXT',
					'notnull' => 0,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'course_id' => [
					'cid' => 3,
					'name' => 'course_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'teacher_id' => [
					'cid' => 4,
					'name' => 'teacher_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'parameter_id' => [
					'cid' => 5,
					'name' => 'parameter_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 6,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 7,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'group_student' => [
			'name' => 'group_student',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'group_id' => [
					'cid' => 1,
					'name' => 'group_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'student_id' => [
					'cid' => 2,
					'name' => 'student_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 3,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 4,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'groups' => [
			'name' => 'groups',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'number' => [
					'cid' => 1,
					'name' => 'number',
					'type' => 'int UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'schedule' => [
					'cid' => 2,
					'name' => 'schedule',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'teacher_id' => [
					'cid' => 3,
					'name' => 'teacher_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'course_semester_id' => [
					'cid' => 4,
					'name' => 'course_semester_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 5,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 6,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'parameters' => [
			'name' => 'parameters',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'parent_id' => [
					'cid' => 1,
					'name' => 'parent_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'wording' => [
					'cid' => 2,
					'name' => 'wording',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'description' => [
					'cid' => 3,
					'name' => 'description',
					'type' => 'TEXT',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'uuid' => [
					'cid' => 4,
					'name' => 'uuid',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'helpers' => [
					'cid' => 5,
					'name' => 'helpers',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => '\'\'',
					'pk' => 0,
				],
				'value' => [
					'cid' => 6,
					'name' => 'value',
					'type' => 'decimal(8,2)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 7,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 8,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'results' => [
			'name' => 'results',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'parameter_id' => [
					'cid' => 1,
					'name' => 'parameter_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'student_id' => [
					'cid' => 2,
					'name' => 'student_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'value' => [
					'cid' => 3,
					'name' => 'value',
					'type' => 'decimal(8,2)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'helpers' => [
					'cid' => 4,
					'name' => 'helpers',
					'type' => 'varchar(255)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 5,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 6,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'schools' => [
			'name' => 'schools',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'name' => [
					'cid' => 1,
					'name' => 'name',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'abbr' => [
					'cid' => 2,
					'name' => 'abbr',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'slug' => [
					'cid' => 3,
					'name' => 'slug',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'address' => [
					'cid' => 4,
					'name' => 'address',
					'type' => 'varchar(255)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 5,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 6,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'semesters' => [
			'name' => 'semesters',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'year' => [
					'cid' => 1,
					'name' => 'year',
					'type' => 'int UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'label' => [
					'cid' => 2,
					'name' => 'label',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'abbr' => [
					'cid' => 3,
					'name' => 'abbr',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'school_id' => [
					'cid' => 4,
					'name' => 'school_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 5,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 6,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'students' => [
			'name' => 'students',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'code' => [
					'cid' => 1,
					'name' => 'code',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'first_name' => [
					'cid' => 2,
					'name' => 'first_name',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'last_name' => [
					'cid' => 3,
					'name' => 'last_name',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'slug' => [
					'cid' => 4,
					'name' => 'slug',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'address' => [
					'cid' => 5,
					'name' => 'address',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'user_id' => [
					'cid' => 6,
					'name' => 'user_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'department_id' => [
					'cid' => 7,
					'name' => 'department_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 8,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 9,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'teachers' => [
			'name' => 'teachers',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'code' => [
					'cid' => 1,
					'name' => 'code',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'first_name' => [
					'cid' => 2,
					'name' => 'first_name',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'last_name' => [
					'cid' => 3,
					'name' => 'last_name',
					'type' => 'NUMERIC',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'slug' => [
					'cid' => 4,
					'name' => 'slug',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'address' => [
					'cid' => 5,
					'name' => 'address',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'user_id' => [
					'cid' => 6,
					'name' => 'user_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'department_id' => [
					'cid' => 7,
					'name' => 'department_id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 8,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 9,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'test' => [
			'name' => 'test',
			'columns' => [
				'Field1' => [
					'cid' => 0,
					'name' => 'Field1',
					'type' => 'INTEGER',
					'notnull' => 0,
					'dflt_value' => NULL,
					'pk' => 1,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
			],
		],
		'users' => [
			'name' => 'users',
			'columns' => [
				'id' => [
					'cid' => 0,
					'name' => 'id',
					'type' => 'bigint UNSIGNED',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 1,
				],
				'name' => [
					'cid' => 1,
					'name' => 'name',
					'type' => 'varchar(255)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'email' => [
					'cid' => 2,
					'name' => 'email',
					'type' => 'varchar(191)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'email_verified_at' => [
					'cid' => 3,
					'name' => 'email_verified_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'password' => [
					'cid' => 4,
					'name' => 'password',
					'type' => 'varchar(255)',
					'notnull' => 1,
					'dflt_value' => NULL,
					'pk' => 0,
				],
				'role' => [
					'cid' => 5,
					'name' => 'role',
					'type' => 'INT',
					'notnull' => 1,
					'dflt_value' => '\'1\'',
					'pk' => 0,
				],
				'remember_token' => [
					'cid' => 6,
					'name' => 'remember_token',
					'type' => 'varchar(100)',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'created_at' => [
					'cid' => 7,
					'name' => 'created_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
				'updated_at' => [
					'cid' => 8,
					'name' => 'updated_at',
					'type' => 'timestamp',
					'notnull' => 0,
					'dflt_value' => 'NULL',
					'pk' => 0,
				],
			],
			'indexes' => [
			],
			'foreign_keys' => [
			],
			'views' => [
				'index' => [
					'name' => 'users__index',
					'columns' => [
						'id' => [
							'cid' => 0,
							'name' => 'id',
							'type' => 'bigint UNSIGNED',
							'notnull' => 0,
							'dflt_value' => NULL,
							'pk' => 0,
						],
						'name' => [
							'cid' => 1,
							'name' => 'name',
							'type' => 'varchar(255)',
							'notnull' => 0,
							'dflt_value' => NULL,
							'pk' => 0,
						],
						'email' => [
							'cid' => 2,
							'name' => 'email',
							'type' => 'varchar(191)',
							'notnull' => 0,
							'dflt_value' => NULL,
							'pk' => 0,
						],
						'role' => [
							'cid' => 3,
							'name' => 'role',
							'type' => 'INT',
							'notnull' => 0,
							'dflt_value' => NULL,
							'pk' => 0,
						],
					],
					'indexes' => [
					],
					'foreign_keys' => [
					],
				],
			],
		],
	],
	'views' => [
	],
	'updated_at' => 1705190378,
];