<?php
/**
 * HTTP Status Codes
 * Generated by ChatGPT for reference
 */
return [
    100 => [
        'status' => 'Informational',
        'code' => 100,
        'message' => 'Continue',
    ],
    101 => [
        'status' => 'Informational',
        'code' => 101,
        'message' => 'Switching Protocols',
    ],
    102 => [
        'status' => 'Informational',
        'code' => 102,
        'message' => 'Processing',
    ],
    103 => [
        'status' => 'Informational',
        'code' => 103,
        'message' => 'Early Hints',
    ],
    200 => [
        'status' => 'Success',
        'code' => 200,
        'message' => 'OK',
    ],
    201 => [
        'status' => 'Success',
        'code' => 201,
        'message' => 'Created',
    ],
    202 => [
        'status' => 'Success',
        'code' => 202,
        'message' => 'Accepted',
    ],
    203 => [
        'status' => 'Success',
        'code' => 203,
        'message' => 'Non-Authoritative Information',
    ],
    204 => [
        'status' => 'Success',
        'code' => 204,
        'message' => 'No Content',
    ],
    205 => [
        'status' => 'Success',
        'code' => 205,
        'message' => 'Reset Content',
    ],
    206 => [
        'status' => 'Success',
        'code' => 206,
        'message' => 'Partial Content',
    ],
    207 => [
        'status' => 'Success',
        'code' => 207,
        'message' => 'Multi-Status',
    ],
    208 => [
        'status' => 'Success',
        'code' => 208,
        'message' => 'Already Reported',
    ],
    226 => [
        'status' => 'Success',
        'code' => 226,
        'message' => 'IM Used',
    ],
    300 => [
        'status' => 'Redirection',
        'code' => 300,
        'message' => 'Multiple Choices',
    ],
    301 => [
        'status' => 'Redirection',
        'code' => 301,
        'message' => 'Moved Permanently',
    ],
    302 => [
        'status' => 'Redirection',
        'code' => 302,
        'message' => 'Found',
    ],
    303 => [
        'status' => 'Redirection',
        'code' => 303,
        'message' => 'See Other',
    ],
    304 => [
        'status' => 'Redirection',
        'code' => 304,
        'message' => 'Not Modified',
    ],
    305 => [
        'status' => 'Redirection',
        'code' => 305,
        'message' => 'Use Proxy',
    ],
    307 => [
        'status' => 'Redirection',
        'code' => 307,
        'message' => 'Temporary Redirect',
    ],
    308 => [
        'status' => 'Redirection',
        'code' => 308,
        'message' => 'Permanent Redirect',
    ],
    400 => [
        'status' => 'Client Error',
        'code' => 400,
        'message' => 'Bad Request',
    ],
    401 => [
        'status' => 'Client Error',
        'code' => 401,
        'message' => 'Unauthorized',
    ],
    402 => [
        'status' => 'Client Error',
        'code' => 402,
        'message' => 'Payment Required',
    ],
    403 => [
        'status' => 'Client Error',
        'code' => 403,
        'message' => 'Forbidden',
    ],
    404 => [
        'status' => 'Client Error',
        'code' => 404,
        'message' => 'Not Found',
    ],
    405 => [
        'status' => 'Client Error',
        'code' => 405,
        'message' => 'Method Not Allowed',
    ],
    406 => [
        'status' => 'Client Error',
        'code' => 406,
        'message' => 'Not Acceptable',
    ],
    407 => [
        'status' => 'Client Error',
        'code' => 407,
        'message' => 'Proxy Authentication Required',
    ],
    408 => [
        'status' => 'Client Error',
        'code' => 408,
        'message' => 'Request Timeout',
    ],
    409 => [
        'status' => 'Client Error',
        'code' => 409,
        'message' => 'Conflict',
    ],
    410 => [
        'status' => 'Client Error',
        'code' => 410,
        'message' => 'Gone',
    ],
    411 => [
        'status' => 'Client Error',
        'code' => 411,
        'message' => 'Length Required',
    ],
    412 => [
        'status' => 'Client Error',
        'code' => 412,
        'message' => 'Precondition Failed',
    ],
    413 => [
        'status' => 'Client Error',
        'code' => 413,
        'message' => 'Payload Too Large',
    ],
    414 => [
        'status' => 'Client Error',
        'code' => 414,
        'message' => 'URI Too Long',
    ],
    415 => [
        'status' => 'Client Error',
        'code' => 415,
        'message' => 'Unsupported Media Type',
    ],
    416 => [
        'status' => 'Client Error',
        'code' => 416,
        'message' => 'Range Not Satisfiable',
    ],
    417 => [
        'status' => 'Client Error',
        'code' => 417,
        'message' => 'Expectation Failed',
    ],
    418 => [
        'status' => 'Client Error',
        'code' => 418,
        'message' => 'I\'m a Teapot',
    ],
    421 => [
        'status' => 'Client Error',
        'code' => 421,
        'message' => 'Misdirected Request',
    ],
    422 => [
        'status' => 'Client Error',
        'code' => 422,
        'message' => 'Unprocessable Entity',
    ],
    423 => [
        'status' => 'Client Error',
        'code' => 423,
        'message' => 'Locked',
    ],
    424 => [
        'status' => 'Client Error',
        'code' => 424,
        'message' => 'Failed Dependency',
    ],
    425 => [
        'status' => 'Client Error',
        'code' => 425,
        'message' => 'Too Early',
    ],
    426 => [
        'status' => 'Client Error',
        'code' => 426,
        'message' => 'Upgrade Required',
    ],
    428 => [
        'status' => 'Client Error',
        'code' => 428,
        'message' => 'Precondition Required',
    ],
    429 => [
        'status' => 'Client Error',
        'code' => 429,
        'message' => 'Too Many Requests',
    ],
    431 => [
        'status' => 'Client Error',
        'code' => 431,
        'message' => 'Request Header Fields Too Large',
    ],
    451 => [
        'status' => 'Client Error',
        'code' => 451,
        'message' => 'Unavailable For Legal Reasons',
    ],
    500 => [
        'status' => 'Server Error',
        'code' => 500,
        'message' => 'Internal Server Error',
    ],
    501 => [
        'status' => 'Server Error',
        'code' => 501,
        'message' => 'Not Implemented',
    ],
    502 => [
        'status' => 'Server Error',
        'code' => 502,
        'message' => 'Bad Gateway',
    ],
    503 => [
        'status' => 'Server Error',
        'code' => 503,
        'message' => 'Service Unavailable',
    ],
    504 => [
        'status' => 'Server Error',
        'code' => 504,
        'message' => 'Gateway Timeout',
    ],
    505 => [
        'status' => 'Server Error',
        'code' => 505,
        'message' => 'HTTP Version Not Supported',
    ],
    506 => [
        'status' => 'Server Error',
        'code' => 506,
        'message' => 'Variant Also Negotiates',
    ],
    507 => [
        'status' => 'Server Error',
        'code' => 507,
        'message' => 'Insufficient Storage',
    ],
    508 => [
        'status' => 'Server Error',
        'code' => 508,
        'message' => 'Loop Detected',
    ],
    510 => [
        'status' => 'Server Error',
        'code' => 510,
        'message' => 'Not Extended',
    ],
    511 => [
        'status' => 'Server Error',
        'code' => 511,
        'message' => 'Network Authentication Required',
    ],
];
